- name: Install k9s with pacman
  pacman: name=k9s state=present
  when: ansible_os_family == "Archlinux"

- name: Install k9s with Homebrew
  homebrew: name=k9s state=present
  when: ansible_os_family == "Darwin"
