git clone git://anongit.freedesktop.org/git/libbsd
git clone git://canonware.com/jemalloc.git
git clone git://git.ghostscript.com/mupdf.git
git clone git://github.com/blindglobe/common-lisp-stat.git
git clone git://github.com/blynn/gitmagic.git
git clone git://github.com/davidgao/LFSCN.git
git clone git://github.com/gjkerns/IPSUR
git clone git://github.com/huyng/bashmarks.git
git clone git://git.netfilter.org/iptables.git
git clone git://pdos.csail.mit.edu/xv6/xv6.git
git clone git://repo.or.cz/lua.git
git clone http://github.com/tomwhite/hadoop-book.git
git clone http://git.oschina.net/jouyouyun/mythesis.git
git clone http://git.oschina.net/whatot/id3-py.git
git clone https://github.com/alibaba/tengine.git
git clone https://github.com/antirez/redis.git
git clone https://github.com/basho/leveldb.git
git clone https://github.com/bos/stanford-cs240h.git
git clone https://github.com/corenominal/cb-pipemenus.git
git clone https://github.com/facebook/tornado.git
git clone https://github.com/gabrielfalcao/sure.git
git clone https://github.com/git/git.git
git clone https://github.com/git-mirror/nginx.git
git clone https://github.com/goagent/goagent.git
git clone https://github.com/huangz1990/annotated_redis_source.git
git clone https://github.com/huangz1990/real-world-haskell-cn.git
git clone https://github.com/iambus/xunlei-lixian.git
git clone https://github.com/ideawu/ssdb.git
git clone https://github.com/ipython/ipython.git
git clone https://github.com/justzx2011/openyoudao.git
git clone https://github.com/kaochenlong/eddie-vim.git
git clone https://github.com/liangdong/Server.git
git clone https://github.com/libevent/libevent
git clone https://github.com/lilydjwg/dotvim.git
git clone https://github.com/longfeey/vundle-vim.git
git clone https://github.com/michaelfairley/mincemeatpy.git
git clone https://github.com/muzuiget/vimfiles
git clone https://github.com/openstack/swift.git
git clone https://github.com/piskvorky/gensim.git
git clone https://github.com/polarssl/polarssl.git
git clone https://github.com/Skylersun/PyMineSweeper.git
git clone https://github.com/soimort/soimort.github.io.git
git clone https://github.com/spf13/spf13-vim.git
git clone https://github.com/tczengming/myvim.git
git clone https://github.com/udonmai/dotfiles.git
git clone https://github.com/vimcn/vimrc.sample.git
git clone https://github.com/whatot/id3-py.git
git clone https://github.com/whatot/magicmethods-zh_CN.git
git clone https://github.com/whatot/string_matching.git
git clone https://github.com/whatot/whatot-dot.git
git clone https://github.com/orangeduck/libCello.git
hg clone https://bitbucket.org/wwq0327/rst
hg clone https://code.google.com/p/ipv6-hosts/
