git clone --recursive git://git.fedorahosted.org/virt-manager.git
git clone --recursive git://git.netfilter.org/iptables.git
git clone --recursive git://github.com/blindglobe/common-lisp-stat.git
git clone --recursive git://github.com/blynn/gitmagic.git
git clone --recursive git://github.com/davidgao/LFSCN.git
git clone --recursive git://pdos.csail.mit.edu/xv6/xv6.git
git clone --recursive git@github.com:whatot/whatot-dot.git
git clone --recursive http://git.oschina.net/whatot/id3-py.git
git clone --recursive http://github.com/jkozera/zeal.git
git clone --recursive http://github.com/tomwhite/hadoop-book.git
git clone --recursive http://gitrepo.org/Liu/algorithms4.git
git clone --recursive https://github.com/0xAX/linux-insides
git clone --recursive https://github.com/78/ssbc
git clone --recursive https://github.com/HardySimpson/zlog
git clone --recursive https://github.com/LiuLang/bcloud
git clone --recursive https://github.com/Skylersun/PyMineSweeper.git
git clone --recursive https://github.com/alibaba/tengine.git
git clone --recursive https://github.com/anjuke/zguide-cn
git clone --recursive https://github.com/antirez/redis.git
git clone --recursive https://github.com/basho/leveldb.git
git clone --recursive https://github.com/bos/stanford-cs240h.git
git clone --recursive https://github.com/bup/bup
git clone --recursive https://github.com/chaconnewu/free-data-science-books
git clone --recursive https://github.com/charliesome/axel
git clone --recursive https://github.com/citusdata/cstore_fdw
git clone --recursive https://github.com/citusdata/file_fdw
git clone --recursive https://github.com/citusdata/postgres_vectorization_test
git clone --recursive https://github.com/cloudwu/bpa
git clone --recursive https://github.com/cloudwu/cstring
git clone --recursive https://github.com/cloudwu/ejoy2d
git clone --recursive https://github.com/corenominal/cb-pipemenus.git
git clone --recursive https://github.com/coreos/fleet
git clone --recursive https://github.com/csev/py4inf
git clone --recursive https://github.com/docopt/docopt.c
git clone --recursive https://github.com/duxing2007/ldd3-examples-3.x
git clone --recursive https://github.com/facebook/libphenom
git clone --recursive https://github.com/facebook/rocksdb
git clone --recursive https://github.com/facebook/tornado.git
git clone --recursive https://github.com/feliscatus/switchyomega
git clone --recursive https://github.com/fogleman/Craft
git clone --recursive https://github.com/fogleman/Craft.git
git clone --recursive https://github.com/gabrielfalcao/sure.git
git clone --recursive https://github.com/git/git.git
git clone --recursive https://github.com/gleitz/howdoi
git clone --recursive https://github.com/harelba/q
git clone --recursive https://github.com/huangz1990/annotated_redis_source.git
git clone --recursive https://github.com/huangz1990/real-world-haskell-cn.git
git clone --recursive https://github.com/iambus/xunlei-lixian.git
git clone --recursive https://github.com/ideawu/ssdb.git
git clone --recursive https://github.com/inconshreveable/ngrok
git clone --recursive https://github.com/jemalloc/jemalloc
git clone --recursive https://github.com/jiacai2050/gooreplacer
git clone --recursive https://github.com/jordansissel/fpm
git clone --recursive https://github.com/joyent/libuv
git clone --recursive https://github.com/justjavac/free-programming-books-zh_CN
git clone --recursive https://github.com/justzx2011/openyoudao.git
git clone --recursive https://github.com/jvns/kernel-module-fun
git clone --recursive https://github.com/kennethreitz/python-guide
git clone --recursive https://github.com/kevinweil/hadoop-lzo
git clone --recursive https://github.com/ktap/ktap
git clone --recursive https://github.com/liangdong/Server.git
git clone --recursive https://github.com/libevent/libevent
git clone --recursive https://github.com/libgit2/libgit2
git clone --recursive https://github.com/mcinglis/c-style
git clone --recursive https://github.com/michaelfairley/mincemeatpy.git
git clone --recursive https://github.com/neovim/neovim.git
git clone --recursive https://github.com/numb3r3/crawler-python
git clone --recursive https://github.com/openstack/swift.git
git clone --recursive https://github.com/orangeduck/libCello
git clone --recursive https://github.com/pbatard/ms-sys
git clone --recursive https://github.com/piskvorky/gensim.git
git clone --recursive https://github.com/polarssl/polarssl.git
git clone --recursive https://github.com/powerline/fonts
git clone --recursive https://github.com/powerline/powerline
git clone --recursive https://github.com/priitj/whitedb
git clone --recursive https://github.com/rupeshk/web2epub
git clone --recursive https://github.com/silentbicycle/greatest
git clone --recursive https://github.com/sjl/learnvimscriptthehardway.git
git clone --recursive https://github.com/smarthosts/smarthosts
git clone --recursive https://github.com/symisc/vedis
git clone --recursive https://github.com/tekknolagi/carp
git clone --recursive https://github.com/torvalds/subsurface.git
git clone --recursive https://github.com/txthinking/google-hosts
git clone --recursive https://github.com/ty4z2008/Qix
git clone --recursive https://github.com/vhf/free-programming-books
git clone --recursive https://github.com/wecite/papers
git clone --recursive https://github.com/whatot/changing.git
git clone --recursive https://github.com/whatot/libbsd.git
git clone --recursive https://github.com/whatot/magicmethods-zh_CN.git
git clone --recursive https://github.com/whatot/pintos.git
git clone --recursive https://github.com/whatot/string_matching.git
git clone --recursive https://github.com/whatot/whatot-dot
git clone --recursive https://github.com/whatot/whatot-io-code
git clone --recursive https://github.com/widuu/chinese_docker
git clone --recursive https://github.com/yeasy/docker_practice
git clone --recursive https://github.com/zeromq/czmq
git clone --recursive https://github.com/zeromq/libzmq
git clone --recursive https://userid@bitbucket.org/openscg/hadoop_fdw.git
hg clone http://hg.nginx.org/nginx
hg clone https://bitbucket.org/wwq0327/rst
hg clone https://code.google.com/p/ipv6-hosts/
