git clone git://git.ghostscript.com/mupdf.git
git clone git://github.com/blindglobe/common-lisp-stat.git
git clone git://github.com/blynn/gitmagic.git
git clone git://github.com/davidgao/LFSCN.git
git clone git://git.netfilter.org/iptables.git
git clone git://pdos.csail.mit.edu/xv6/xv6.git
git clone http://github.com/tomwhite/hadoop-book.git
git clone http://git.oschina.net/jouyouyun/mythesis.git
git clone http://git.oschina.net/whatot/id3-py.git
git clone http://gitrepo.org/Liu/algorithms4.git
git clone http://luajit.org/git/luajit-2.0.git
git clone https://github.com/alibaba/tengine.git
git clone https://github.com/anjuke/zguide-cn
git clone https://github.com/antirez/redis.git
git clone https://github.com/basho/leveldb.git
git clone https://github.com/bos/stanford-cs240h.git
git clone https://github.com/chaconnewu/free-data-science-books
git clone https://github.com/cloudwu/bpa
git clone https://github.com/cloudwu/cstring
git clone https://github.com/cloudwu/ejoy2d
git clone https://github.com/corenominal/cb-pipemenus.git
git clone https://github.com/docopt/docopt.c
git clone https://github.com/duxing2007/ldd3-examples-3.x
git clone https://github.com/emiraga/axel
git clone https://github.com/facebook/libphenom
git clone https://github.com/facebook/rocksdb
git clone https://github.com/facebook/tornado.git
git clone https://github.com/fogleman/Craft.git
git clone https://github.com/gabrielfalcao/sure.git
git clone https://github.com/gleitz/howdoi
git clone https://github.com/goagent/goagent.git
git clone https://github.com/HardySimpson/zlog
git clone https://github.com/huangz1990/annotated_redis_source.git
git clone https://github.com/huangz1990/real-world-haskell-cn.git
git clone https://github.com/iambus/xunlei-lixian.git
git clone https://github.com/ideawu/ssdb.git
git clone https://github.com/jemalloc/jemalloc
git clone https://github.com/justzx2011/openyoudao.git
git clone https://github.com/kennethreitz/python-guide
git clone https://github.com/ktap/ktap
git clone https://github.com/liangdong/Server.git
git clone https://github.com/libevent/libevent
git clone https://github.com/libgit2/libgit2
git clone https://github.com/mcinglis/c-style
git clone https://github.com/michaelfairley/mincemeatpy.git
git clone https://github.com/openstack/swift.git
git clone https://github.com/orangeduck/libCello
git clone https://github.com/piskvorky/gensim.git
git clone https://github.com/polarssl/polarssl.git
git clone https://github.com/priitj/whitedb
git clone https://github.com/sjl/learnvimscriptthehardway.git
git clone https://github.com/Skylersun/PyMineSweeper.git
git clone https://github.com/torvalds/subsurface.git
git clone https://github.com/vhf/free-programming-books
git clone https://github.com/whatot/changing.git
git clone https://github.com/whatot/libbsd.git
git clone https://github.com/whatot/magicmethods-zh_CN.git
git clone https://github.com/whatot/pintos.git
git clone https://github.com/whatot/string_matching.git
git clone https://github.com/whatot/whatot-dot.git
git clone https://github.com/zeromq/czmq
git clone https://github.com/zeromq/libzmq
hg clone http://hg.nginx.org/nginx
hg clone https://bitbucket.org/wwq0327/rst
hg clone https://code.google.com/p/ipv6-hosts/
