repos:
  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        entry: mise exec -- shellcheck -x
        language: system
        types: [shell]
        exclude: ^home/dot_zsh/vendor/
      - id: shfmt
        name: shfmt
        entry: mise exec -- shfmt -w -i 2 -ci
        language: system
        types: [shell]
        exclude: ^home/dot_zsh/vendor/
      - id: dprint
        name: dprint
        entry: mise exec -- dprint fmt
        language: system
        types_or: [json, yaml, markdown, toml]
