cask "macvim-app"
cask "ghostty"
cask "iina"
cask "notunes"
cask "jordanbaird-ice"
cask "keepingyouawake"
cask "readest"
cask "omnidisksweeper"
cask "telegram"
cask "sequel-ace"
cask "input-source-pro"
cask "mole"

cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-lxgw-wenkai"
cask "font-sarasa-gothic"
