brew "discount"
brew "cmake"
brew "docker-completion"
brew "ninja"
brew "nushell"
brew "openjdk"
brew "plantuml"
brew "protobuf"
brew "aliyun-cli"
brew "libpq"
brew "editorconfig"

cask "orbstack"
cask "cc-switch"
cask "codex"
cask "codex-app"
cask "zed"
