brew "discount"
brew "cc-switch"
brew "cmake"
brew "docker-completion"
brew "ninja"
brew "nushell"
brew "openjdk"
brew "plantuml"
brew "protobuf"
brew "aliyun-cli"
brew "libpq"
brew "editorconfig"

cask "sequel-ace"
