name = "macos-arm64"
os = "macos"
arch = "arm64"

packages = ["base", "desktop", "dev"]
devtools = ["rust-toolchain", "rust-tools", "go-tools"]

[vim]
profile = "tiny"

[kitty]
font_size = 13
shell = "/opt/homebrew/bin/fish --login"
