- import_tasks: install_zsh.yml

# Configuration
- name: Check if zshrc already exists
  stat: path="{{dotfiles_user_home}}/.zshrc"
  register: zshrc_stat

- name: Back up zshrc if it exists
  command: mv ~/.zshrc ~/.zshrc.bak
  args:
    creates: "{{dotfiles_user_home}}/.zshrc.bak"
  when: zshrc_stat.stat.exists

- import_tasks: prezto.yml
