---
# main tasks file for arch

- name: Set the Asia/Shanghai timezone
  file:
    src: "/usr/share/zoneinfo/Asia/Shanghai"
    dest: /etc/localtime
    state: link
    force: yes

- include_tasks: mirror.yml
- include_tasks: user.yml
- include_tasks: pkg.yml

- name: Ensure basic services is running and enabled
  service: name='{{ item }}' state=started enabled=yes
  with_items:
    - fstrim.timer
    - systemd-timesyncd

- name: Disable sshd service
  service: name=sshd state=stopped enabled=no

- name: Set default jdk
  shell: archlinux-java set {{ default_jdk }}

- name: Sysctl configs
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - { name: "vm.swappiness", value: 2 }
    - { name: "fs.inotify.max_user_watches", value: 524288 }
