---
# main tasks file for arch

- name: Set the Asia/Shanghai timezone
  file:
    src: "/usr/share/zoneinfo/Asia/Shanghai"
    dest: /etc/localtime
    state: link
    force: yes

- include_tasks: mirror.yml
- include_tasks: user.yml
- include_tasks: pkg.yml

- name: Ensure basic services is running and enabled
  service: name='{{ item }}' state=started enabled=yes
  with_items:
    - fstrim.timer
    - ntpd

- name: Disable sshd service
  service: name=sshd state=stopped enabled=no

- name: Set openjdk9 as default java
  shell: archlinux-java set java-9-openjdk

- name: Use sysctl to setup vm.swappiness
  sysctl: name="vm.swappiness" value=2 sysctl_set=yes state=present reload=yes
