---
# tasks file for arch-mirror

- name: Config archlinuxcn in pacman.conf
  blockinfile:
    dest: /etc/pacman.conf
    block: |
      [archlinuxcn]
      SigLevel = Optional TrustedOnly
      Server = https://mirrors.ustc.edu.cn/archlinuxcn/$arch

- debug: var=ansible_distribution

- name: Using ustc mirror in /etc/pacman.d/mirrorlist in Archlinux
  shell: sed -i '/ustc/s/^#//' /etc/pacman.d/mirrorlist
  when: ansible_distribution == "Archlinux"

- name: Setup /etc/pacman-mirrors.conf in Manjaro
  lineinfile:
    regexp: '^OnlyCountry = China$'
    line: 'OnlyCountry = China'
    dest: /etc/pacman-mirrors.conf
    state: present
    insertafter: EOF
  when: ansible_distribution == "Manjaro Linux"
  register: pacman_mirrors_conf_updated

- name: Update /etc/pacman.d/mirrorlist by pacman-mirrors in Manjaro
  shell: pacman-mirrors
  when: ansible_distribution == "Manjaro Linux" and
        (pacman_mirrors_conf_updated | changed)
