---
# mirror tasks file for arch

- name: Check /etc/pacman.conf
  stat:
    path: /etc/pacman.conf
  register: pacman_conf_file

- name: Config archlinuxcn in pacman.conf
  blockinfile:
    dest: /etc/pacman.conf
    block: |
      [archlinuxcn]
      SigLevel = Optional TrustedOnly
      Server = https://mirrors.ustc.edu.cn/archlinuxcn/$arch
      Server = https://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/$arch
      #Server = https://cdn.repo.archlinuxcn.org/$arch
  when: pacman_conf_file.stat.exists == True

- name: Check /etc/pacman.d/mirrorlist
  stat:
    path: /etc/pacman.d/mirrorlist
  register: pacman_mirrorlist_file

- name: Uncomment ustc mirror in /etc/pacman.d/mirrorlist
  replace:
    path: /etc/pacman.d/mirrorlist
    regexp: '^#(.*ustc.*)'
    replace: '\1'
  when: pacman_mirrorlist_file.stat.exists == True

- name: Check /etc/pacman-mirrors.conf
  stat:
    path: /etc/pacman-mirrors.conf
  register: pacman_mirrors_conf_file

- name: Setup stable branch in /etc/pacman-mirrors.conf
  replace:
    dest: /etc/pacman-mirrors.conf
    regexp: '^Branch = testing$'
    replace: 'Branch = stable'
  when: pacman_mirrors_conf_file.stat.exists == True
  register: pacman_mirrors_conf_file_updated

- name: Update /etc/pacman.d/mirrorlist by pacman-mirrors
  shell: pacman-mirrors -a -B stable -c China --timeout 1
  when: pacman_mirrors_conf_file_updated is changed

- name: Ensure archlinux-keyring and archlinuxcn-keyring were installed
  community.general.pacman:
    name:
      - archlinux-keyring
      - archlinuxcn-keyring
    state: present
    update_cache: true
