---
# mirror tasks file for arch

- name: Check /etc/pacman.conf
  stat:
    path: /etc/pacman.conf
  register: pacman_conf_file

- name: Config archlinuxcn in pacman.conf
  blockinfile:
    dest: /etc/pacman.conf
    block: |
      [archlinuxcn]
      SigLevel = Optional TrustedOnly
      Server = https://mirrors.ustc.edu.cn/archlinuxcn/$arch
      #Server = https://cdn.repo.archlinuxcn.org/$arch
  when: pacman_conf_file.stat.exists == True

- name: Check /etc/pacman.d/mirrorlist
  stat:
    path: /etc/pacman.d/mirrorlist
  register: pacman_mirrorlist_file

- name: Uncomment ustc mirror in /etc/pacman.d/mirrorlist
  replace:
    path: /etc/pacman.d/mirrorlist
    regexp: '^#(.*ustc.*)'
    replace: '\1'
  when: pacman_mirrorlist_file.stat.exists == True

- name: Check /etc/pacman-mirrors.conf
  stat:
    path: /etc/pacman-mirrors.conf
  register: pacman_mirrors_conf_file

- name: Setup testing branch in /etc/pacman-mirrors.conf
  replace:
    dest: /etc/pacman-mirrors.conf
    regexp: '^Branch = stable$'
    replace: 'Branch = testing'
  when: pacman_mirrors_conf_file.stat.exists == True
  register: pacman_mirrors_conf_file_updated

- name: Update /etc/pacman.d/mirrorlist by pacman-mirrors
  shell: pacman-mirrors --branch testing --country China --timeout 1
  when: pacman_mirrors_conf_file_updated | changed
