---
# pkg tasks file for arch

- name: Update and Upgrade the system
  pacman: update_cache=yes upgrade=yes

#- name: Uninstall unneeded packages
#  pacman: name='{{ absent_pkgs }}' state=absent recurse=yes

- name: Install fonts packages
  pacman: name='{{ font_pkgs }}' state=present

- name: Special packages need install from AUR
  debug: var=aur_pkgs

- name: Summary all needed package names
  set_fact:
    all_pkgs: "{{ all_pkgs }} + [ '{{ item }}' ]"
  with_items:
    - '{{ backend_pkgs }}'
    - '{{ basic_pkgs }}'
    - '{{ c_pkgs }}'
    - '{{ erlang_elixir_pkgs }}'
    - '{{ java_pkgs }}'
    - '{{ program_tool_pkgs }}'
    - '{{ python_pkgs }}'
    - '{{ rust_pkgs }}'
    - '{{ view_pkgs }}'
    - '{{ write_pkgs }}'
    - '{{ haskell_pkgs }}'
    - '{{ fq_pkgs }}'

- name: Install all needed packages
  pacman: name='{{ all_pkgs }}' state=present

- name: Link files in /etc/dnsmasq.d to /etc/networkmanager/dnsmasq.d
  file:
    src: '/etc/dnsmasq.d/{{ item | basename }}'
    dest: '/etc/NetworkManager/dnsmasq.d/{{ item | basename}}'
    state: link
  with_fileglob: '/etc/dnsmasq.d/*'

- name: Configure NetworkManager.conf
  copy:
    content: |
      # Configuration file for NetworkManager.
      # See "man 5 NetworkManager.conf" for details.
      [main]
      dns=dnsmasq
    dest: /etc/NetworkManager/NetworkManager.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
