---
# pkg tasks file for arch

- name: Update and Upgrade the system
  pacman: update_cache=yes upgrade=yes

- name: Uninstall unneeded packages
  pacman: name='{{ item }}' state=absent
  with_items:
    - '{{ absent_pkgs }}'
  when: absent_pkgs is defined

- name: Install fonts packages
  pacman: name='{{ item }}' state=latest
  with_items:
    - '{{ font_pkgs }}'
  when: font_pkgs is defined

- name: Special packages need install from AUR
  debug: var=aur_pkgs
  when: aur_pkgs is defined

- name: Install packages
  pacman: name='{{ item }}' state=latest
  with_flattened:
    - '{{ backend_pkgs }}'
    - '{{ basic_pkgs }}'
    - '{{ c_pkgs }}'
    - '{{ erlang_elixir_pkgs }}'
    - '{{ haskell_pkgs }}'
    - '{{ java_pkgs }}'
    - '{{ program_tool_pkgs }}'
    - '{{ python_pkgs }}'
    - '{{ rust_pkgs }}'
    - '{{ view_pkgs }}'

- name: Link files in /etc/dnsmasq.d to /etc/networkmanager/dnsmasq.d
  file:
    src: '/etc/dnsmasq.d/{{ item | basename }}'
    dest: '/etc/NetworkManager/dnsmasq.d/{{ item | basename}}'
    state: link
  with_fileglob: '/etc/dnsmasq.d/*'

- name: Configure NetworkManager
  file:
    src: NetworkManager.conf
    dest: /etc/NetworkManager/NetworkManager.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
