---
# pkg tasks file for arch

- name: Update and Upgrade the system
  pacman: update_cache=yes upgrade=yes

- name: Show toClean packages
  debug: var=absent_pkgs
- name: Uninstall unneeded packages
  pacman: name='{{ absent_pkgs }}' state=absent

- name: Show fonts packages
  debug: var=font_pkgs
- name: Install fonts packages
  pacman: name='{{ font_pkgs }}' state=present

- name: Show packages need installed from AUR
  debug: var=aur_pkgs

- name: Show basic packages
  debug: var=basic_pkgs
- name: Install basic packages
  pacman: name='{{ basic_pkgs }}' state=present

- name: Show programming packages
  debug: var=program_tool_pkgs
- name: Install programming packages
  pacman: name='{{ program_tool_pkgs }}' state=present

- name: Show fq packages
  debug: var=fq_pkgs
- name: Install fq packages
  pacman: name='{{ fq_pkgs }}' state=present

- name: Link files in /etc/dnsmasq.d to /etc/networkmanager/dnsmasq.d
  file:
    src: "/etc/dnsmasq.d/{{ item | basename }}"
    dest: "/etc/NetworkManager/dnsmasq.d/{{ item | basename}}"
    state: link
  with_fileglob: "/etc/dnsmasq.d/*"

- name: Configure NetworkManager.conf
  copy:
    content: |
      # Configuration file for NetworkManager.
      # See "man 5 NetworkManager.conf" for details.
      [main]
      dns=dnsmasq
    dest: /etc/NetworkManager/NetworkManager.conf
    owner: root
    group: root
    mode: "0644"
    backup: true
