---
# pkg tasks file for arch

- name: Update and Upgrade the system
  pacman: update_cache=yes upgrade=yes

- name: Uninstall unneeded packages
  pacman: name='{{ item }}' state=absent
  with_items:
    - '{{ absent_pkgs }}'
  when: absent_pkgs is defined

- name: Install fonts packages
  pacman: name='{{ item }}' state=latest
  with_items:
    - '{{ font_pkgs }}'
  when: font_pkgs is defined

- name: Special packages need install from AUR
  debug: var=aur_pkgs
  when: aur_pkgs is defined

- name: Install packages
  pacman: name='{{ item }}' state=latest
  with_flattened:
    - '{{ backend_pkgs }}'
    - '{{ basic_pkgs }}'
    - '{{ haskell_pkgs }}'
    - '{{ java_pkgs }}'
    - '{{ program_tool_pkgs }}'
    - '{{ python_pkgs }}'
    - '{{ view_pkgs }}'
