---
# user tasks file for arch

- name: Ensure wheel group exists
  group: name=wheel state=present

- name: Config wheel group
  lineinfile:
    dest: /etc/sudoers.d/20_wheel
    regexp: "^%wheel"
    line: "%wheel  ALL=(ALL)  NOPASSWD: ALL"
    state: present
    backup: true
    insertafter: EOF
    create: true
    owner: root
    group: root
    mode: 0440

- name: Manage default user
  user:
    name: "{{ default_user }}"
    groups: wheel
    append: true
    state: present
