if [[ -d "/usr/share/oh-my-zsh/" ]];then
    ZSH=/usr/share/oh-my-zsh/
    DISABLE_AUTO_UPDATE="true"
else
    ZSH=~/.oh-my-zsh/
    DISABLE_AUTO_UPDATE="false"
fi

if [[ -v WSL_INTEROP ]]; then
    hostip=$(cat /etc/resolv.conf | grep nameserver | awk '{ print $2 }')
    export PROXY_HOST=${hostip}
    echo "wsl2 proxy: ${PROXY_HOST} "
else
    export PROXY_HOST="127.0.0.1"
    echo "local proxy: ${PROXY_HOST} "
fi

function unsetproxy() {
    unset ALL_PROXY
    unset HTTP_PROXY
    unset HTTPS_PROXY
    unset all_proxy
    unset http_proxy
    unset https_proxy
}
function setproxy() {
    unsetproxy
    export ALL_PROXY="socks5://${PROXY_HOST}:7891"
    export HTTP_PROXY="http://${PROXY_HOST}:7890"
    export HTTPS_PROXY="http://${PROXY_HOST}:7890"
}
function proxyinfo() {
    echo "ALL_PROXY =" ${ALL_PROXY}
    echo "HTTP_PROXY =" ${HTTP_PROXY}
    echo "HTTPS_PROXY =" ${HTTPS_PROXY}
}

# turn on proxy by default
setproxy

case `uname` in
    Darwin)
        ZSH_THEME="robbyrussell"
        source ~/.zshenv
        alias vim='mvim -v'
        SCCACHE_WRAPPER="/usr/local/bin/sccache"
        export HOMEBREW_NO_AUTO_UPDATE=1
    ;;
    Linux)
        ZSH_THEME="gentoo"
        export GTK_IM_MODULE=fcitx
        export QT_IM_MODULE=fcitx
        export XMODIFIERS="@im=fcitx"
        alias gvim='gvim -c "call Maximize_Window()"'
        alias unzipp='unzip -O cp936'
        SCCACHE_WRAPPER="/usr/bin/sccache"
    ;;
esac

plugins=(git colorize cargo common-aliases kubectl sdk)

alias mvalidate="mvn validate -U"
alias mdeploy='mvn clean deploy -Dmaven.test.skip=true'
alias mtree='mvn clean dependency:tree -U'
alias msource='mvn dependency:sources'

alias mqc='mvn compile --offline'
alias mcc='mvn clean compile -U'
alias mcco='mvn clean compile -U --offline'

alias mqt='mvn test -DfailIfNoTests=false --offline'
alias mtt='mvn clean test -U -DfailIfNoTests=false'
alias mtto='mvn clean test -U -DfailIfNoTests=false --offline'

alias myip="curl myip.ipip.net"

unset GREP_OPTIONS
export MESA_GL_VERSION_OVERRIDE=2.1
export XDG_CONFIG_HOME="$HOME/.config/"
export LC_MESSAGES="en_US.UTF-8"
export EDITOR='vim'

ZSH_CACHE_DIR=$HOME/.oh-my-zsh-cache
if [[ ! -d $ZSH_CACHE_DIR ]]; then
    mkdir $ZSH_CACHE_DIR
fi

PY_ENV_WRAPPER=/usr/bin/virtualenvwrapper.sh
if [[ -f $PY_ENV_WRAPPER ]]; then
    source $PY_ENV_WRAPPER
    export WORKON_HOME="$HOME/envs/"
fi

if [[ -f $SCCACHE_WRAPPER ]]; then
    export RUSTC_WRAPPER="${SCCACHE_WRAPPER}"
fi

export SDKMAN_DIR="$HOME/.sdkman"
export SDKMAN_JDK8="8.0.265.hs-adpt"
export SDKMAN_JDK11="11.0.8.hs-adpt"
export SDKMAN_JDKX="15.0.0.hs-adpt"

if [[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]]; then
    source "$SDKMAN_DIR/bin/sdkman-init.sh"
    # sdk offline enable
    function usejdk8() {
        sdk use java "${SDKMAN_JDK8}"
    }
    function usejdk11() {
        sdk use java "${SDKMAN_JDK11}"
    }
    function usejdkx() {
        sdk use java "${SDKMAN_JDKX}"
    }
fi
function init_sdkman() {
    curl -s "https://get.sdkman.io" | bash
    sdk install java "${SDKMAN_JDK8}"
    sdk install java "${SDKMAN_JDK11}"
    sdk install java "${SDKMAN_JDKX}"
    sdk list java
    sdk current java
}

source $ZSH/oh-my-zsh.sh
