- name: Install gvim by pacman
  pacman: name=gvim state=present
  when: ansible_os_family == "Archlinux"

- name: Install macvim in MacOS
  homebrew: name=macvim state=present
  when: ansible_os_family == "Darwin"

# mkdir -p ~/.vim/{plugged,sessions,undodir,autoload}
- name: Makes sure all vim sub directory exists
  file: path="{{dotfiles_user_home}}/.vim/{{ item }}" state=directory
  with_items:
    - plugged
    - sessions
    - undodir
    - autoload

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{dotfiles_user_home}}/.vim/autoload/plug.vim"

- name: Check if vimrc exists
  stat: path="{{dotfiles_user_home}}/.vimrc"
  register: vimrc_stat
  failed_when: False

- name: Backup vimrc
  command: mv ~/.vimrc ~/.vimrc.bak
  args:
    creates: "{{dotfiles_user_home}}/.vimrc.bak"
  when: vimrc_stat.stat.exists

- name: Symlink vimrc
  file:
    src: "{{ dotfiles_home }}/roles/vim/files/tiny.vim"
    dest: "{{dotfiles_user_home}}/.vimrc"
    state: link

- name: Install plugins
  command: vim +PlugInstall +qall
